// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nation.proto

package com.iicanf.model.enums.Nation;

public final class NationOuterClass {
  private NationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Nation}
   */
  public enum Nation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHINA = 0;</code>
     */
    CHINA(0),
    /**
     * <code>JAPAN = 1;</code>
     */
    JAPAN(1),
    /**
     * <code>AMERICA = 2;</code>
     */
    AMERICA(2),
    /**
     * <code>CANADA = 3;</code>
     */
    CANADA(3),
    /**
     * <code>RUSSIA = 4;</code>
     */
    RUSSIA(4),
    /**
     * <code>INDIA = 5;</code>
     */
    INDIA(5),
    /**
     * <code>KORORA = 6;</code>
     */
    KORORA(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CHINA = 0;</code>
     */
    public static final int CHINA_VALUE = 0;
    /**
     * <code>JAPAN = 1;</code>
     */
    public static final int JAPAN_VALUE = 1;
    /**
     * <code>AMERICA = 2;</code>
     */
    public static final int AMERICA_VALUE = 2;
    /**
     * <code>CANADA = 3;</code>
     */
    public static final int CANADA_VALUE = 3;
    /**
     * <code>RUSSIA = 4;</code>
     */
    public static final int RUSSIA_VALUE = 4;
    /**
     * <code>INDIA = 5;</code>
     */
    public static final int INDIA_VALUE = 5;
    /**
     * <code>KORORA = 6;</code>
     */
    public static final int KORORA_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Nation valueOf(int value) {
      return forNumber(value);
    }

    public static Nation forNumber(int value) {
      switch (value) {
        case 0: return CHINA;
        case 1: return JAPAN;
        case 2: return AMERICA;
        case 3: return CANADA;
        case 4: return RUSSIA;
        case 5: return INDIA;
        case 6: return KORORA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Nation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Nation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Nation>() {
            public Nation findValueByNumber(int number) {
              return Nation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.iicanf.model.enums.Nation.NationOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Nation[] VALUES = values();

    public static Nation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Nation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Nation)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014nation.proto*Z\n\006Nation\022\t\n\005CHINA\020\000\022\t\n\005J" +
      "APAN\020\001\022\013\n\007AMERICA\020\002\022\n\n\006CANADA\020\003\022\n\n\006RUSSI" +
      "A\020\004\022\t\n\005INDIA\020\005\022\n\n\006KORORA\020\006B\037\n\035com.iicanf" +
      ".model.enums.Nationb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
