// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.iicanf.model.User;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>bool is_delete = 3;</code>
     */
    boolean getIsDelete();

    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    boolean hasInsertTime();
    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    com.google.protobuf.Timestamp getInsertTime();
    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    boolean hasUpdateTime();
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    com.google.protobuf.Timestamp getUpdateTime();
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

    /**
     * <code>string phone = 6;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 6;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>.Nation nation = 7;</code>
     */
    int getNationValue();
    /**
     * <code>.Nation nation = 7;</code>
     */
    com.iicanf.model.enums.Nation.NationOuterClass.Nation getNation();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      age_ = 0;
      isDelete_ = false;
      phone_ = "";
      nation_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readUInt32();
              break;
            }
            case 24: {

              isDelete_ = input.readBool();
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (insertTime_ != null) {
                subBuilder = insertTime_.toBuilder();
              }
              insertTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(insertTime_);
                insertTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updateTime_ != null) {
                subBuilder = updateTime_.toBuilder();
              }
              updateTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updateTime_);
                updateTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              nation_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iicanf.model.User.UserOuterClass.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iicanf.model.User.UserOuterClass.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iicanf.model.User.UserOuterClass.User.class, com.iicanf.model.User.UserOuterClass.User.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>uint32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int IS_DELETE_FIELD_NUMBER = 3;
    private boolean isDelete_;
    /**
     * <code>bool is_delete = 3;</code>
     */
    public boolean getIsDelete() {
      return isDelete_;
    }

    public static final int INSERT_TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp insertTime_;
    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    public boolean hasInsertTime() {
      return insertTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    public com.google.protobuf.Timestamp getInsertTime() {
      return insertTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp insert_time = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder() {
      return getInsertTime();
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp updateTime_;
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    public boolean hasUpdateTime() {
      return updateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      return getUpdateTime();
    }

    public static final int PHONE_FIELD_NUMBER = 6;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 6;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATION_FIELD_NUMBER = 7;
    private int nation_;
    /**
     * <code>.Nation nation = 7;</code>
     */
    public int getNationValue() {
      return nation_;
    }
    /**
     * <code>.Nation nation = 7;</code>
     */
    public com.iicanf.model.enums.Nation.NationOuterClass.Nation getNation() {
      com.iicanf.model.enums.Nation.NationOuterClass.Nation result = com.iicanf.model.enums.Nation.NationOuterClass.Nation.valueOf(nation_);
      return result == null ? com.iicanf.model.enums.Nation.NationOuterClass.Nation.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeUInt32(2, age_);
      }
      if (isDelete_ != false) {
        output.writeBool(3, isDelete_);
      }
      if (insertTime_ != null) {
        output.writeMessage(4, getInsertTime());
      }
      if (updateTime_ != null) {
        output.writeMessage(5, getUpdateTime());
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, phone_);
      }
      if (nation_ != com.iicanf.model.enums.Nation.NationOuterClass.Nation.CHINA.getNumber()) {
        output.writeEnum(7, nation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, age_);
      }
      if (isDelete_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isDelete_);
      }
      if (insertTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInsertTime());
      }
      if (updateTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUpdateTime());
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, phone_);
      }
      if (nation_ != com.iicanf.model.enums.Nation.NationOuterClass.Nation.CHINA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, nation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iicanf.model.User.UserOuterClass.User)) {
        return super.equals(obj);
      }
      com.iicanf.model.User.UserOuterClass.User other = (com.iicanf.model.User.UserOuterClass.User) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getIsDelete()
          == other.getIsDelete());
      result = result && (hasInsertTime() == other.hasInsertTime());
      if (hasInsertTime()) {
        result = result && getInsertTime()
            .equals(other.getInsertTime());
      }
      result = result && (hasUpdateTime() == other.hasUpdateTime());
      if (hasUpdateTime()) {
        result = result && getUpdateTime()
            .equals(other.getUpdateTime());
      }
      result = result && getPhone()
          .equals(other.getPhone());
      result = result && nation_ == other.nation_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + IS_DELETE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDelete());
      if (hasInsertTime()) {
        hash = (37 * hash) + INSERT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getInsertTime().hashCode();
      }
      if (hasUpdateTime()) {
        hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateTime().hashCode();
      }
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + NATION_FIELD_NUMBER;
      hash = (53 * hash) + nation_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iicanf.model.User.UserOuterClass.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iicanf.model.User.UserOuterClass.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.iicanf.model.User.UserOuterClass.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iicanf.model.User.UserOuterClass.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iicanf.model.User.UserOuterClass.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iicanf.model.User.UserOuterClass.User.class, com.iicanf.model.User.UserOuterClass.User.Builder.class);
      }

      // Construct using com.iicanf.model.User.UserOuterClass.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        isDelete_ = false;

        if (insertTimeBuilder_ == null) {
          insertTime_ = null;
        } else {
          insertTime_ = null;
          insertTimeBuilder_ = null;
        }
        if (updateTimeBuilder_ == null) {
          updateTime_ = null;
        } else {
          updateTime_ = null;
          updateTimeBuilder_ = null;
        }
        phone_ = "";

        nation_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iicanf.model.User.UserOuterClass.internal_static_User_descriptor;
      }

      public com.iicanf.model.User.UserOuterClass.User getDefaultInstanceForType() {
        return com.iicanf.model.User.UserOuterClass.User.getDefaultInstance();
      }

      public com.iicanf.model.User.UserOuterClass.User build() {
        com.iicanf.model.User.UserOuterClass.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iicanf.model.User.UserOuterClass.User buildPartial() {
        com.iicanf.model.User.UserOuterClass.User result = new com.iicanf.model.User.UserOuterClass.User(this);
        result.name_ = name_;
        result.age_ = age_;
        result.isDelete_ = isDelete_;
        if (insertTimeBuilder_ == null) {
          result.insertTime_ = insertTime_;
        } else {
          result.insertTime_ = insertTimeBuilder_.build();
        }
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        result.phone_ = phone_;
        result.nation_ = nation_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iicanf.model.User.UserOuterClass.User) {
          return mergeFrom((com.iicanf.model.User.UserOuterClass.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iicanf.model.User.UserOuterClass.User other) {
        if (other == com.iicanf.model.User.UserOuterClass.User.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getIsDelete() != false) {
          setIsDelete(other.getIsDelete());
        }
        if (other.hasInsertTime()) {
          mergeInsertTime(other.getInsertTime());
        }
        if (other.hasUpdateTime()) {
          mergeUpdateTime(other.getUpdateTime());
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (other.nation_ != 0) {
          setNationValue(other.getNationValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iicanf.model.User.UserOuterClass.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iicanf.model.User.UserOuterClass.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>uint32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>uint32 age = 2;</code>
       */
      public Builder setAge(int value) {

        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 age = 2;</code>
       */
      public Builder clearAge() {

        age_ = 0;
        onChanged();
        return this;
      }

      private boolean isDelete_ ;
      /**
       * <code>bool is_delete = 3;</code>
       */
      public boolean getIsDelete() {
        return isDelete_;
      }
      /**
       * <code>bool is_delete = 3;</code>
       */
      public Builder setIsDelete(boolean value) {

        isDelete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_delete = 3;</code>
       */
      public Builder clearIsDelete() {

        isDelete_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp insertTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> insertTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public boolean hasInsertTime() {
        return insertTimeBuilder_ != null || insertTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public com.google.protobuf.Timestamp getInsertTime() {
        if (insertTimeBuilder_ == null) {
          return insertTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
        } else {
          return insertTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public Builder setInsertTime(com.google.protobuf.Timestamp value) {
        if (insertTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          insertTime_ = value;
          onChanged();
        } else {
          insertTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public Builder setInsertTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (insertTimeBuilder_ == null) {
          insertTime_ = builderForValue.build();
          onChanged();
        } else {
          insertTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public Builder mergeInsertTime(com.google.protobuf.Timestamp value) {
        if (insertTimeBuilder_ == null) {
          if (insertTime_ != null) {
            insertTime_ =
              com.google.protobuf.Timestamp.newBuilder(insertTime_).mergeFrom(value).buildPartial();
          } else {
            insertTime_ = value;
          }
          onChanged();
        } else {
          insertTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public Builder clearInsertTime() {
        if (insertTimeBuilder_ == null) {
          insertTime_ = null;
          onChanged();
        } else {
          insertTime_ = null;
          insertTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getInsertTimeBuilder() {

        onChanged();
        return getInsertTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getInsertTimeOrBuilder() {
        if (insertTimeBuilder_ != null) {
          return insertTimeBuilder_.getMessageOrBuilder();
        } else {
          return insertTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : insertTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp insert_time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
          getInsertTimeFieldBuilder() {
        if (insertTimeBuilder_ == null) {
          insertTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getInsertTime(),
                  getParentForChildren(),
                  isClean());
          insertTime_ = null;
        }
        return insertTimeBuilder_;
      }

      private com.google.protobuf.Timestamp updateTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public boolean hasUpdateTime() {
        return updateTimeBuilder_ != null || updateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public com.google.protobuf.Timestamp getUpdateTime() {
        if (updateTimeBuilder_ == null) {
          return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        } else {
          return updateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateTime_ = value;
          onChanged();
        } else {
          updateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder setUpdateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updateTimeBuilder_ == null) {
          updateTime_ = builderForValue.build();
          onChanged();
        } else {
          updateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (updateTime_ != null) {
            updateTime_ =
              com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
          } else {
            updateTime_ = value;
          }
          onChanged();
        } else {
          updateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public Builder clearUpdateTime() {
        if (updateTimeBuilder_ == null) {
          updateTime_ = null;
          onChanged();
        } else {
          updateTime_ = null;
          updateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {

        onChanged();
        return getUpdateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
        if (updateTimeBuilder_ != null) {
          return updateTimeBuilder_.getMessageOrBuilder();
        } else {
          return updateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp update_time = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
          getUpdateTimeFieldBuilder() {
        if (updateTimeBuilder_ == null) {
          updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdateTime(),
                  getParentForChildren(),
                  isClean());
          updateTime_ = null;
        }
        return updateTimeBuilder_;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 6;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 6;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 6;</code>
       */
      public Builder clearPhone() {

        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 6;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        phone_ = value;
        onChanged();
        return this;
      }

      private int nation_ = 0;
      /**
       * <code>.Nation nation = 7;</code>
       */
      public int getNationValue() {
        return nation_;
      }
      /**
       * <code>.Nation nation = 7;</code>
       */
      public Builder setNationValue(int value) {
        nation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Nation nation = 7;</code>
       */
      public com.iicanf.model.enums.Nation.NationOuterClass.Nation getNation() {
        com.iicanf.model.enums.Nation.NationOuterClass.Nation result = com.iicanf.model.enums.Nation.NationOuterClass.Nation.valueOf(nation_);
        return result == null ? com.iicanf.model.enums.Nation.NationOuterClass.Nation.UNRECOGNIZED : result;
      }
      /**
       * <code>.Nation nation = 7;</code>
       */
      public Builder setNation(com.iicanf.model.enums.Nation.NationOuterClass.Nation value) {
        if (value == null) {
          throw new NullPointerException();
        }

        nation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Nation nation = 7;</code>
       */
      public Builder clearNation() {

        nation_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.iicanf.model.User.UserOuterClass.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iicanf.model.User.UserOuterClass.User();
    }

    public static com.iicanf.model.User.UserOuterClass.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.iicanf.model.User.UserOuterClass.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\037google/protobuf/timestamp." +
      "proto\032\014nation.proto\"\276\001\n\004User\022\014\n\004name\030\001 \001" +
      "(\t\022\013\n\003age\030\002 \001(\r\022\021\n\tis_delete\030\003 \001(\010\022/\n\013in" +
      "sert_time\030\004 \001(\0132\032.google.protobuf.Timest" +
      "amp\022/\n\013update_time\030\005 \001(\0132\032.google.protob" +
      "uf.Timestamp\022\r\n\005phone\030\006 \001(\t\022\027\n\006nation\030\007 " +
      "\001(\0162\007.NationB\027\n\025com.iicanf.model.Userb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.iicanf.model.enums.Nation.NationOuterClass.getDescriptor(),
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Name", "Age", "IsDelete", "InsertTime", "UpdateTime", "Phone", "Nation", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.iicanf.model.enums.Nation.NationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
